name: Deploy (PRs)
on:
  pull_request_target: # Use pull_request_target to ensure the workflow has access to secrets
    types: [opened, reopened, synchronize, closed] # Use pull_request_target for security reasons

permissions:
  contents: write # To push to the gh-pages branch
  pull-requests: write # To comment on the PR with the preview URL

jobs:
  deploy_pr_preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # When using pull_request_target, you need to explicitly fetch the
          # PR's head ref to get the correct code from the fork.
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Install and Build
        run: npm ci

      - name: Build static site
        run: npm run build
        env:
          BASE_URL: /${{ github.event.repository.name }}/pr-previews/${{ github.event.number }}/

      - name: Deploy PR Preview to GitHub Pages
        # Don't deploy if PR is closed
        if: github.event.action != 'closed'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          # This is the target directory within the publish_branch where the action places the contents of your built project
          destination_dir: pr-previews/${{ github.event.number }} # Deploy to a unique subdirectory for each PR
